basePath: /api
consumes:
    - application/json
info:
    description: '## Автоматизация продаж'
    title: CRM
    version: 0.0.1
paths:
    /auth/login:
        post:
            description: |-
                ## Роут предназначен для авторизации ранее зарегистрированного пользователя
                Используемый <b>Authorization Flow</b> подразумевает проверку введенных пользователем <b>credential</b> (email, password)
            operationId: authLogin
            parameters:
                - in: body
                  name: Body
                  schema:
                      properties:
                          password:
                              default: '!Qwerty123'
                              description: |-
                                  Пароль
                                  
                                  in: query
                              type: string
                              x-go-name: Password
                          email:
                              default: "admin@crm.space"
                              description: |-
                                  Почта
                                  
                                  in: query
                              type: string
                              x-go-name: Email
                      required:
                          - email
                          - password
                      type: object
            responses:
                "200":
                    description: '## Успешная авторизаиця'
                    schema:
                        $ref: '#/responses/success/schema'
                "400":
                    description: |-
                        ## Неверный запрос
                        Возможно, вам стоит перепроверить введенные данные

                        Все возможные сообщения об ошибках в полезной нагрузке (payload):
                        <ul>=
                          <li>Неправильный логин или пароль</li>
                          <li>Одно или несколько полей пустые</li>
                        </ul>
                    schema:
                        $ref: '#/responses/badRequest/schema'
                "429":
                    description: |-
                        ## Retry Limit Exceeded
                        Количество попыток: <code>4</code>
                        Сбросить лимит после <code>5 минуты</code>
                    schema:
                        $ref: '#/responses/retryLimitExceeded/schema'
                "500":
                    description: Internal Server Error or Something went wrong
                    schema:
                        $ref: '#/responses/internalServer/schema'
            summary: Вход в платформу
            tags:
                - Authorization

produces:
    - application/json
responses:
    accessDenied:
        description: ""
        schema:
            properties:
                message:
                    example: access is denied
                    type: string
                    x-go-name: Message
                payload:
                    example: "null"
                    x-go-name: Payload
            type: object
    badRequest:
        description: ""
        schema:
            properties:
                message:
                    example: bad request
                    type: string
                    x-go-name: Message
                payload:
                    example: "null"
                    x-go-name: Payload
            type: object
    conflict:
        description: ""
        schema:
            properties:
                message:
                    example: conflict
                    type: string
                    x-go-name: Message
                payload:
                    example: "null"
                    x-go-name: Payload
            type: object
    internalServer:
        description: ""
        schema:
            properties:
                message:
                    example: internal server error
                    type: string
                    x-go-name: Message
                payload:
                    example: "null"
                    x-go-name: Payload
            type: object
    notFound:
        description: ""
        schema:
            properties:
                message:
                    example: notFound
                    type: string
                    x-go-name: Message
                payload:
                    example: "null"
                    x-go-name: Payload
            type: object
    notImplementation:
        description: ""
        schema:
            properties:
                message:
                    example: not implementation
                    type: string
                    x-go-name: Message
                payload:
                    example: "null"
                    x-go-name: Payload
            type: object
    retryLimitExceeded:
        description: ""
        schema:
            properties:
                message:
                    example: retry limit exceeded
                    type: string
                    x-go-name: Message
                payload:
                    example: "null"
                    x-go-name: Payload
            type: object
    somethingWentWrong:
        description: ""
        schema:
            properties:
                message:
                    example: something went wrong
                    type: string
                    x-go-name: Message
                payload:
                    example: "null"
                    x-go-name: Payload
            type: object
    success:
        description: ""
        schema:
            properties:
                message:
                    example: success
                    type: string
                    x-go-name: Message
                payload:
                    example: "null"
                    x-go-name: Payload
            type: object
    unauthorized:
        description: ""
        schema:
            properties:
                message:
                    example: unauthorized
                    type: string
                    x-go-name: Message
                payload:
                    example: "null"
                    x-go-name: Payload
            type: object
securityDefinitions:
    bearer:
        in: header
        name: Authorization
        type: apiKey
swagger: "2.0"
